### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jluisperez** [Huemul/trae#226]
Hola,

Lo primero enhorabuena por este estupendo desarrollo. Deciros que no soy un mega experto en la materia, pero estoy intentando utilizar vuestra librería, contra mi API REST (desarrollada en Java), y me encuentro con un problema al acceder vía POST a uno de mis métodos:

```
Error
    at u (trae.umd.min.js?fdb7:1)
    at eval (trae.umd.min.js?fdb7:1)
```

desde un componente Vue.

Si lo intento directamente con FETCH:

```js
const url = 'http://192.168.10.1:8080/myapp/nuix/login/user/password/2'

fetch(url, {
    method: 'POST'
}).then(response => response.json()).then(data => console.log(data));
```

obtengo la respuesta perfecta en JSON, pero con 'trae':

```js
return nuixService.post('/login/user/password/2')
        .then(function (res) {
            return res.data
        })
```

siendo `nuixService`:

```js
const nuixService = trae.create({
    baseUrl: configService.dsrUrl
})
```

y `configService`:

```js
const configService = {    
    dsrUrl: 'http://192.168.10.1:8080/myapp/nuix'
}
```

Muy agradecido si me pueden orientar, quizá no estoy haciendo algo bien. Saludos.

**Comment by gillchristian** [comment]
Hola @jluisperez 

Es difícil sin más contexto saber cuál sería el problema.

Si puedes reproducir el error en [CodeSandbox](https://codesandbox.io) quizá te podríamos ayudar.

**Comment by jluisperez** [comment]
Es complicado, porque la API es totalmente privada, y dependiente de una licencia dongle que no se puede exponer en internet. Haré más pruebas para ver si doy con el problema, podría ser falta de parámetros al ejecutar POST con trae? En realidad mi API solo espera una URL, sin parámetros. Saludos

**Comment by gillchristian** [comment]
No hace falta que uses la misma API, con que se reproduzca el error usando alguna API pública seríá suficiente ([aquí hay una](https://reqres.in) por ejemplo). El problema es que con la información que nos has dado lástimosamente mucho no podemos hacer.

**Comment by jluisperez** [comment]
hola, como te comentaba estoy lejos de ser un experto... he codificado esto en CodeSandbox:
https://codesandbox.io/s/xenodochial-agnesi-n3zjx
contra el API que me recomiendas, pero no veo por consola el resultado... en este caso utilizo un método get, y los parámetros se los paso hardcoedados... no se si es correcto... muchas gracias

**Comment by jluisperez** [comment]
> No hace falta que uses la misma API, con que se reproduzca el error usando alguna API pública seríá suficiente ([aquí hay una](https://reqres.in) por ejemplo). El problema es que con la información que nos has dado lástimosamente mucho no podemos hacer.

Hola de nuevo, pudiste echarle un ojo a mi código en Codesandbox?

**Comment by gillchristian** [comment]
Si, hay un error en el request. Lo [puedes ver aqui](https://codesandbox.io/s/modest-raman-c8vl2?expanddevtools=1&fontsize=14&module=%2Fsrc%2Fservicios%2Fprueba.js).

Si haces lo mismo en el código de tu app (log de las propiedades que tiene el objeto de error en el `.catch`). Para entender más que contiene la respuesta y el error puedes [ver la documentación](https://github.com/Huemul/trae#response).

El problema del lado de **trae** es que el error no tiene un mensaje porque el servidor no responde con `statusText` así que eso deberiamos arreglar (empezamos a trabajar en la v2 estos días y esos arreglos irán ahí).

Voy a cerrar este issue y queda #227 abierto como reporte del problema
