### ISSUE TITLE
v2 - Further build improvements

### ISSUE THREAD

**Issue by gillchristian** [Huemul/trae#331]
#329 set the build in the right direction.

Some things that we can iterate over

- [ ] ~~If it's possible, output only one `.d.ts` file and do it on the root (`index.d.ts`).~~ I checked the TS config docs and didn't find anything related to this. Let's leave it as is.
- [x] Add UMD build. To support [unpkg](https://unpkg.com/).
- [x] Add a `tsconfing.build.json`. The default one is used by editors and other tools. We can extend from that one but change what we are excluding (like tests). Only difference at the moment 🤔
- [ ] Remove all comments from the output files

EDIT: comment on `.d.ts`

**Comment by ianaya89** [comment]
Will take a look to this 👁

**Comment by gillchristian** [comment]
I just found this: https://github.com/jaredpalmer/tsdx

We might be able to abstract all the build stuff

**Comment by gillchristian** [comment]
Solved by #333
