### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by gillchristian** [Huemul/trae#70]
I've started to use TypeScript at work, and even though the project was not setup with `trae` I want to add it so having the TS typings would be really cool, not only for me but for everybody interested in using the library.

**Comment by ndelvalle** [comment]
This issue does not apply anymore. Version 2 ships with TS. We still need to add TS to the whole codebase but this will be related to a new and more specific issue.

**Comment by fjbardelli** [comment]
Is v2 ready for production, how is the npm command to install
